version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  command-test-syft:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - sbom/install:
          version: v0.11.0 # Version of Manifest CLI to install
          generator: syft # syft, cdxgen, etc.
          generator_version: v0.91.0 # Syft requires an explicit version be set.
      - sbom/generate:
          generator: syft # Should match the installed generator
          source: .
          source_name: circleci_test
          source_version: 1.0.0
          labels: test,circleci,orb
  command-test-cdxgen:
    docker:
      - image: cimg/node:lts
    steps:
      - sbom/install:
          version: v0.11.0 # Version of Manifest CLI to install
          generator: cdxgen # syft, cdxgen, etc.
          # generator_version: v1.2.3 # Optionally install a specific version of the generator (default: latest)
      - sbom/generate:
          generator: cdxgen # Should match the installed generator
          source: .
          source_name: circleci_test
          source_version: 1.0.0
          labels: test,circleci,orb
          passthrough_args: "--spec-version 1.4"
workflows:
  test-deploy:
    jobs:
      - command-test-syft:
          filters: *filters
      - command-test-cdxgen:
          filters: *filters
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: manifest/sbom
          vcs_type: gh # << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - command-test-syft
            - command-test-cdxgen
          context: <publishing-context>
          filters: *release-filters
